name: CI/CD Pipeline

on:
  push:
    branches:
      - main

jobs:
  build-and-push:
    runs-on: ubuntu-latest  # Replace with desired runner OS (e.g., ubuntu-latest)

    steps:
      - uses: actions/checkout@v2  # Checkout code from repository

      - name: Login to Docker Hub (optional)
        if: ${{ secrets.DOCKER_USERNAME && secrets.DOCKER_PASSWORD }}  # Check for Docker Hub credentials
        run: |
          docker login -u $DOCKER_USERNAME -p $DOCKER_PASSWORD

      - name: Build and push images
        run: |
          for service in front-end-react order-service user-service mongo; do
            docker build -t ${{ secrets.DOCKER_USERNAME }}/$service -f ./$service/Dockerfile .
            if [[ ${{ secrets.DOCKER_USERNAME }]]; then
              docker push ${{ secrets.DOCKER_USERNAME }}/$service
            fi
          done
